Safer docker retries

diff --git a/deploy/template/etc/default/docker b/deploy/template/etc/default/docker
--- a/deploy/template/etc/default/docker
+++ b/deploy/template/etc/default/docker
@@ -23,20 +23,24 @@ fi
 echo "Formating 'instance_storage' as ext4"
 
 # Format logical volume with ext4
-if ! mkfs.ext4 /dev/instance_storage/all;
+if ! df -T /dev/mapper/instance_storage-all | grep 'ext4';
 then
-    echo "Could not format 'instance_storage' as ext4."
-    # Wait for the logical volume to become ready to be formatted.
-    # Small wait is better than zombie node.
-    sleep 5
-    exit 1
+  if ! mkfs.ext4 /dev/instance_storage/all;
+  then
+      echo "Could not format 'instance_storage' as ext4."
+      # Wait for the logical volume to become ready to be formatted.
+      # Small wait is better than zombie node.
+      sleep 5
+      exit 1
+  else
+      echo "Succesfully formated 'instance_storage' as ext4."
+      echo "Mounting logical volume"
+      # Mount on /mnt
+      mount /dev/instance_storage/all /mnt
+  fi
 else
-    echo "Succesfully formated 'instance_storage' as ext4."
+  echo "Already mounted..."
 fi
-
-echo "Mounting logical volume"
-# Mount on /mnt
-mount /dev/instance_storage/all /mnt
 
 echo "Creating docker specific directories"
 mkdir -p /mnt/var/lib/docker
@@ -50,8 +54,13 @@ host=$(curl $META/public-hostname)
 key_root=/mnt/docker_keys
 
 # Generate the keys
-mkdir -p $key_root
-dockerkeys.sh $host $key_root
+
+if [ ! -d $key_root ];
+then
+  mkdir -p $key_root
+  dockerkeys.sh $host $key_root
+fi
+
 
 DOCKER_OPTS=" -g /mnt/var/lib/docker -s aufs"
 DOCKER_OPTS="$DOCKER_OPTS --tlsverify --tlscacert=$key_root/ca.pem"
@@ -59,4 +68,5 @@ DOCKER_OPTS="$DOCKER_OPTS --tlscert=$key_root/server-cert.pem"
 DOCKER_OPTS="$DOCKER_OPTS --tlskey=$key_root/server-key.pem"
 DOCKER_OPTS="$DOCKER_OPTS -H $host:2376"
 
+# Random sleep wait for network to be ready?
 export DOCKER_OPTS
